### ISSUE TITLE
Autotag and symbolic links

### ISSUE THREAD

**Issue by mrmodolo** [StrumentiResistenti/Tagsistant#13]
Hi!

If I create a symbolic link to a file (an image for example), no automatic tag is created. When I copy the same file everything works as expected.

Thanks,
Marcelo Módolo

**Comment by StrumentiResistenti** [comment]
Hi mrmodolo!

I'll try to reproduce this behaviour and I'll investigate this. Tagsistant 0.8.2 hosted here on github is experimental and under development. So, reporting bugs and unexpected behaviours is highly welcome, but if you need stability for production, please use Tagsistant 0.8.1a available on tagsistant.net

**Comment by mrmodolo** [comment]
Hi!

I have the same behavior with version 0.8.1a! 

Thanks,
Marcelo Módolo

**Comment by StrumentiResistenti** [comment]
I've fixed this on the latest copy of 0.8.1 on SVN. I'll merge this fix in 0.8.2 on GitHub ASAP.
