### ISSUE TITLE
recycle bin

### ISSUE THREAD

**Issue by milahu** [StrumentiResistenti/Tagsistant#16]
i miss an optional 'recycle bin',
to undelete / recycle / recover files,
to undo / rollback mistakes.

'In computing, the trash (also known as the recycle bin and by other names) is temporary storage for files that have been deleted in a file manager by the user, but not yet permanently erased from the file system. Typically, a recycle bin is presented as a special file directory to the user (whether or not it is actually a single directory depends on the implementation), allowing the user to browse deleted files, undelete those that were deleted by mistake, or delete them permanently (either one by one, or by the "Empty Trash" function).'
https://en.wikipedia.org/wiki/Trash_%28computing%29

**Comment by StrumentiResistenti** [comment]
This is an interesting suggestion. The trash could be implemented as a special tag, like the ALL/ tag. Every object ready for deletion could be instead tagged as .trash/, or something similar. This way, trash could be a feature a user could decide to activate when mounting Tagsistant. I'll work on this, thanks.

**Comment by StrumentiResistenti** [comment]
I've implemented the idea of a trash bin by adding a special tag called '.Trash' (mind the dot). This special tag is applied to every object (file, dir, whatever) that is getting deleted from its last tag. So if file 'test' is tagged as t1/ and t2/ and you do:

    $ rm store/t1/t2/@/test

test is not deleted from disk but it receives the .Trash/ tag instead. If you later do a:

    $ rm store/.Trash/@/test

this time the test file gets actually deleted. Please do some testing and let me know if it works properly.

**Comment by StrumentiResistenti** [comment]
By the way, deleting the .Trash tag from tags/ or store/ is silently ignored and the tag gets created at mountpoint so if your repo has been created by an old version of Tagsistant, the tag will appear automatically at next mount.

Just remember to add "-t" or "--enable-trash" on command line. It's not enabled by default.
