### ISSUE TITLE
append only (access control)

### ISSUE THREAD

**Issue by milahu** [StrumentiResistenti/Tagsistant#17]
optionally allow only appending of files.
similar to an 'incoming' directory.
purpose: minimize risk of data loss.

i failed with xattr (extended file attributes):
> $ tagsistant --enable-xattr tsa_rep tsa_mnt
> $ chattr +a tsa_mnt
> chattr: Inappropriate ioctl for device while reading flags on tsa_mnt
> $ sudo chattr +a tsa_mnt
> chattr: Permission denied while trying to stat tsa_mnt

**Comment by StrumentiResistenti** [comment]
The --enable-xattr switch enables POSIX ACL support. It's not intended for Ext2/3/4 specific extensions.
