### ISSUE TITLE
[bug] cannot compile without libextract

### ISSUE THREAD

**Issue by fbarriga** [StrumentiResistenti/Tagsistant#21]
After executing `./configure` without having _libextract_ a message will be displayed but the script will end without issues. When trying to compile it will fail due the missing _libextract_ headers.

So now there are 2 options:
a) Make _libextract_ optional: this will require multiple changes
b) Make _libextract_ mandatory: see the following patch:

```
diff --git a/configure.ac b/configure.ac
index f3b9ab3..58f8ec5 100644
--- a/configure.ac
+++ b/configure.ac
@@ -111,6 +111,7 @@ AC_CHECK_LIB([extractor],[EXTRACTOR_loadDefaultLibraries],[use_libextractor='0.5
                echo "libextractor is a universal metadata extractor. Tagsistant uses it"
                echo "to autotag your files."
                echo "More info at http://http://www.gnu.org/software/libextractor"
+               AC_MSG_FAILURE(["libextractor not found"])
        ])
 ])

```

**Comment by StrumentiResistenti** [comment]
I suppose that I'll go for the second option ASAP, and plan the first for a future release. After all libextractor is required for autotagging only and I suppose there are users interested in Tagsistant but not in autotagging. Thus, forcing them to install libextractor should be avoided.

Thank you very much for reporting.

**Comment by StrumentiResistenti** [comment]
I've patched configure.ac to include AC_MSG_FAILURE(["libextractor not found"]). Could you please check it?
