### ISSUE TITLE
help needed: cannot compile on fedora, libgthread support not available, but glib2 installed

### ISSUE THREAD

**Issue by conrad-heimbold** [StrumentiResistenti/Tagsistant#22]
Hi everybody, 

could someone help me installing tagsistant on Fedora? ./configure gives out as error: "GThread support not available. Please install libgthread", however according to this website https://rpmfind.net/linux/rpm2html/search.php?query=libgthread-2.0.so.0 I think that the dnf package glib2 (which is installed), does provide the same functionality as libgthread. 

Thank you for your help in advance!

**Comment by StrumentiResistenti** [comment]
Hi, the GLib package is the right one. Have you installed the corresponding -devel package?

**Comment by conrad-heimbold** [comment]
Thank you very much, that was the problem. I just always needed to add "-devel" for all those packages (libextractor, glib2, fuse, etc.)!
