### ISSUE TITLE
Cannot compile with automake-1.15, /usr/share/automake-..../ltmain.sh missing in version 1.15 vs. 1.14

### ISSUE THREAD

**Issue by conrad-heimbold** [StrumentiResistenti/Tagsistant#23]
See commit a883cb6a8fca850f4ceb22c7eead406039c9862f

**Comment by conrad-heimbold** [comment]
Do you know how to use autoreconf , to fix the errors coming up when using libtoolize (libtool) and changing the symlinks to /usr/share/libtool/build-aux/... ? I got the following error when running ./configure : configure: error: cannot run /bin/sh ./config.sub .

**Comment by conrad-heimbold** [comment]
"Workaround" kind of thing (that I have not yet get to work completely) is to use libtool and changing the symlinks (pointing to /usr/share/automake-1.14/... ) to point instead to /usr/share/libtool/build-aux/... (Replace ... with install-sh, ltmain, compile, depcomp, etc.).

**Comment by StrumentiResistenti** [comment]
First of all, I'm not an autotools expert. That said, I usually invoke the autogen.sh script available in the repository root and everything usually get fixed. Have you tried this? The script basically does this:

```
aclocal
autoheader
libtoolize
automake -a
autoconf
```

If you have any suggestion on a better way to use autotools, please feel free to share it.

**Comment by conrad-heimbold** [comment]
Ah thanks, I forgot the autogen.sh . I thought configure, make and make install are enough; but obviously not :D
