### ISSUE TITLE
My files do not get auto-tagged. 

### ISSUE THREAD

**Issue by conrad-heimbold** [StrumentiResistenti/Tagsistant#26]
Hello everybody, unfortunately, my files do not get auto-tagged (doesn't matter which file type). I don't know why. I couldn't get any error, not even when starting tagsistant with --debug=p . The complete ```--verbose``` debug log is quite long; maybe there is some error message somewhere; at least I could not find it. Should I post it? 
If I put for example an mp3 file inside ```$MP/store/test/@``` , no ```$MP/store/audio:``` gets created (with the appropriate sub-folders). Do I have to activate it somewhere? Or is there any special folder where I have to put the file? 

I am using the most current version of tagsistant, I cloned it from github and compiled. 
My libextractor version is libextractor-1.3-8.fc24.x86_64 . 

Please help!

**Comment by StrumentiResistenti** [comment]
This is the kernel on the tp_mp3.c plugin:

```
    /* default tagging */
    tagsistant_sql_tag_object(qtree->dbi, "audio", NULL, NULL, qtree->inode);

    /* applying regular expression */
    tagsistant_plugin_iterator(qtree, "audio:", keywords, keyword_counter, rx);

    return(TP_STOP);
```

So you get an `audio` simple tag and all the tags extracted by libextract, which you can preview using the `extract` command on the file you're saving inside Tagsistant, provided the MP3 tag matches the plugin regexp which can be customized in the `repository.ini` file:

```
[mime:audio/mpeg]
filter=^(year|album|artist)$
```

So, do you have the `audio` simple tag? This is not related to libextract. Second: do you have any triple tag in the `audio:` namespace added to your file?

**Comment by conrad-heimbold** [comment]
Neither the tag "audio", nor " audio:" gets created automatically. Do you mean I should create the "audio" (not "audio:") tag manually? The tag " audio:" was not already there when moving the file, therefore also no sub-"tags" aka properties & values of the namespace "audio".

**Comment by StrumentiResistenti** [comment]
No, automatic tags are created for you. There's no need to declare tags or namespaces, keys and values first. For some reason the autotagging stack does not kick in. I'll check ASAP.

**Comment by conrad-heimbold** [comment]
Thank you very much!

**Comment by conrad-heimbold** [comment]
Can I force auto-tagging with some command?

**Comment by conrad-heimbold** [comment]
I meant to say: can I manually run the plug-in to generate the tags?

**Comment by StrumentiResistenti** [comment]
If you `touch` a file inside `store/`, it is reprocessed, but I expect the autotagging MP3 plugin to not produce its expected effects as it didn't when you tagged the file the very first time.
