### ISSUE TITLE
incorrect handling of .tags files and garbled internal state

### ISSUE THREAD

**Issue by BrainDamage** [StrumentiResistenti/Tagsistant#27]
tagsistant has multiple bugs regarding .tags files
first of all, it reports even nonexisting .tags files to be existing and readable:
```
$ test -r store/ALL/@/wat
$ echo $?
1
$ test -r store/ALL/@/wat.tags
$ echo $?
0
$ cat store/ALL/@/wat.tags
cat: store/ALL/@/wat.tags: Bad address
```
worse, as soon as we tested for readability, we've effectively made tagsistant stuck in some apparent internal infinite loop/deadlock for any access on the store directory
```
$ ls store
^C^C^C^C
```
the same happens if someone tries to copy in a file into a tag query or creating a new tag, etc
the only way to get the command to return is to kill tagsistant's process

EDIT:
extra infos:
```
$ tagsisant --version
Tagsistant (tagfs) v.0.8.1a (codename: Berlin)
Build: 565.20141118.000022 FUSE_USE_VERSION: 26
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```
EDIT2:
I've tested git head 1c779dc33377edac891129e5cddebd19177ec629 and while the test bug remains, tagsistant doesn't get stuck anymore on a failed read, IMHO the hang is a nasty enough bug that should warrant a new release when possible

**Comment by StrumentiResistenti** [comment]
Thanks for reporting. I've committed a fix on GitHub repo. Could you please check it? I'll pack a new release as soon as possible.

**Comment by BrainDamage** [comment]
thanks for the quick fix, it does indeed work properly now
