### ISSUE TITLE
Multiple issues with the project site tagsistant.net 

### ISSUE THREAD

**Issue by abernatskiy** [StrumentiResistenti/Tagsistant#36]
Hi,

Wanted to download the stable version of tagsistant and couldn't. All download links land on a page reporting the following error:

0 - Call to undefined function split()

Tried mailing you with the form provided on the website and it was broken as well. Gave the following error:

Could not instantiate mail function.

Contacting you mostly just in case you don't know, but would be thankful if the issues were fixed.

-Anton

**Comment by StrumentiResistenti** [comment]
I've just migrated the site to another provider and a newer version of PHP. I didn't knew that split() has been deprecated since PHP 5.3.0. Now the download page should work again. Thanks for reporting.
