### ISSUE TITLE
can't look for two triple tags in one query

### ISSUE THREAD

**Issue by meloxu** [StrumentiResistenti/Tagsistant#4]
Hey, I only just startet using tagsistant and I'm still not really fluent ...
However I found that if I try to query more than one triple tag tagsistant strikes.
E.g. there are no folders in store/blabla:/time/eq/2000/blumblum:/ 
For some reason I can cd into store/blabla:/time/eq/2000/blumblum:/color/eq/red/@/ though. Only, I have to manually type the path. Neither nautilus nur cd with autocompletion nor ls show any folders in store/blabla:/time/eq/2000/blumblum:/  .

Any idea as to why this is the case?

P.S. I can go through several normal tags but as soon as I entered one triple tag the next one wont work.

**Comment by StrumentiResistenti** [comment]
Hi, I'm not able to reproduce the bug. I've used the latest version of Tagsistant and have created your triple tags. Using TAB I can complete every token of the path store/blabla:/time/eq/2000/blumblum:/color/eq/red/@/. And I can navigate it with Nautilus. Which version of Tagsistant are you using? Is it the one from this repository or one of the compiled version from tagsistant.net?

Thanks.
