### ISSUE TITLE
feature request: alias symlinks to change operator precedence

### ISSUE THREAD

**Issue by michael-ts** [StrumentiResistenti/Tagsistant#46]
I would like the ability to create a query that looks something like this:

(A OR B) AND (C OR D)

But the way aliases currently work is such that if I created an alias A_B=A/+/B and an alias C_D=C/+D and then try to use =A_B/=C_D it's going to instead resolve to:

A OR (B AND C) OR D

What I think would make more sense is that if a symlink was created in alias, it would effectively perform the grouping operator, e.g.

cd alias
ln -s A/+/B A_B
ln -s C/+/D C_D

Now what this should do is make store/=A_B/=C_D resolve as (A OR B) AND (C OR D).

**Comment by StrumentiResistenti** [comment]
Aliases are actually managed by literally replacing their value inside the query. After the replacement happened, the query is resolved in its final, expanded form. Your query:

  `A or B and C or D`

is resolved creating three SQL temporary tables: one for "A", another for "B and C" and a third one for "D". Then a UNION blends the results of all the tables which are later dropped, after returning all the results.

Probably your goal can be achieved using **tag groups**.

If you want all the files tagged A/B together with all the files tagged C/D, you can write this as:

  `store/{/A/B/}/+/{/C/D/}/@`

While if you want all the files tagged A/C or A/D or B/C or B/D, this should be served by the query:

  `store/{/A/B/}/{/C/D/}/@`

The +/ in the middle matters.

Hope this helps.

**Comment by michael-ts** [comment]
@StrumentiResistenti Somehow I missed that tag groups are essentially an Or.  Thanks!
