### ISSUE TITLE
Build fails under Ubuntu 14.04

### ISSUE THREAD

**Issue by gpolitis** [StrumentiResistenti/Tagsistant#6]
Running ./autogen.sh gives:

    aclocal: error: aclocal: file 'm4/lt~obsolete.m4' does not exist
    aclocal.m4:17: warning: this file was generated for autoconf 2.68.
    You have another version of autoconf.  It may work, but is not guaranteed to.
    If you have problems, you may need to regenerate the build system entirely.
    To do so, use the procedure documented by the package, typically `autoreconf'.

Running autoreconf gives:

    aclocal: error: aclocal: file 'm4/lt~obsolete.m4' does not exist
    autoreconf: aclocal failed with exit status: 1

Not sure what's the best way to fix this. Unfortunately autoconf 2.68 is not available in Ubuntu 14.04.

**Comment by StrumentiResistenti** [comment]
I'm sorry, I overlooked this note. I'm not an Autotool guru at all. But I'm building Tagsistant on an Ubuntu 14.04 and a 15.04 too without any problems. What version does Ubuntu 14.04 provides. I'm on a 15.04 right now and here it's autoconf 2.69-8 (the number after the dash should be the Ubuntu subrelease, I suppose).
